import google.cloud.storage
storage_client = google.cloud.storage.Client.from_service_account_json('cred.json')
bucket = storage_client.get_bucket('mcsur-a0dd2.appspot.com')

image_name = "biker-without-helmet"

# Generate Path for the text file generated by YOLOv5


def generatePath(image_name):
    return r'MCSurv\\exp\\crops\\number-plate\\' + image_name + '.jpg'


imageBlob = bucket.blob("/")
imagePath = generatePath(image_name)
imageBlob = bucket.blob("recent.jpg")
imageBlob.upload_from_filename(imagePath)  # Upload your image
